### ISSUE TITLE
I'm still confused!

### ISSUE THREAD

**Issue by briancullinan** [ChromeDevTools/awesome-chrome-devtools#66]
This looks like an awesome resource!  I think I am just missing a bit of a starting point.

Here's what I am trying to do:
1) Record clicks in context of a browser tab (done, have an extension loading in page space attached to window events)
2) Generate selenium commands from a template
3) Send script to background service for translation
4) Connect to webdriver for script re-executing

Basically making an event recording service for QA, and I am missing some connections.  How do I connect selenium to an existing DevTools remote session?
https://github.com/auchenberg/devtools-remote

I've also tried this:
http://elementalselenium.com/tips/29-chrome-driver

Would it make more sense to cut out selenium entirely and translate my chromedriver commands back to DevTools?

The rest of our team relies on http://webdriver.io/, so it seems like this path would be rewriting part of that tool to translate directly to chrome.

**Comment by Garbee** [comment]
This repository is just to help promote good community projects related to the DevTools. It is not for general support about the tools or any of the recommended packages. 

Please reach out to the given software maintainer of what you're using for support. Also try StackOverflow for general support.

Thank you.

**Comment by megamindbrian** [comment]
Hahaha, "Good Community -- go somewhere else".  Thanks for nothing!

**Comment by paulirish** [comment]
https://twitter.com/klamping/status/912398422652735488 looks like part of your pipeline.

i also know testim.io was working on something similar.

**Comment by megamindbrian** [comment]
Cool, thank you for sharing!  Yes, that does look very similar, I am
actually trying to reimplement the part where the window opens with a new
session.  I want to click a button in a plugin and have the automation
debugger run in the current window.

**Comment by megamindbrian** [comment]
I think I figured it out. A browser extension can run a little express server. It will answer requests based on the webdriver wire protocol, then convert that to debugger commands the same way chromedriver does. That way I can click a playback button within my browser window and see the test in action without launching a new tab.

**Comment by megamindbrian** [comment]
The opposite of selenium-standalone? Is there a plugin that already does this?

**Comment by Garbee** [comment]
Going through and cleaning some stuff up (sorry haven't been very attentive to this repo lately.)

Looking at this again, the Kantu link redirects to its evolved service. That is not open source it seems, so it isn't something we'd be open to referencing here. (I'll work on getting our contributing doc updated to reflect this since it seems missing.) The goal here is to provide exposure to projects that excel at their offering and have open code-bases for educating others.

We also link to projects and not Q&A topics on other sites/forums. It seems like you've found the kind of solutions you need, so I'm closing this issue on out.

Thank you.
